version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "SenhaForte@123"
      MSSQL_TCP_ENFORCE_ENCRYPTION: "0"
    ports:
      - "1433:1433"
    networks:
      - app-network

  app:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
