version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "uma-chave-secreta-em-producao-mais-complexa"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network

  api:
    build:
      context: ./Estoque-API
    container_name: estoque-api
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
