version: '3.8'
services:
#  db:
#    image: mcr.microsoft.com/mssql/server:2022-latest
#    environment:
#      SA_PASSWORD: "yourPassword123"
#      ACCEPT_EULA: "Y"
#    ports:
#      - "1433:1433"

  api:
    build: .
#    depends_on:
#      - db
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
